[package]
name = "cid-web"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
description = "Local web server for cid"

[dependencies]
backhand = "0.23.0"
cid-base = { path = "../base", version = "0.1.1" }
cid-daemon = { path = "../daemon", version = "0.1.1" }
cid-pal = { path = "../pal", version = "0.1.1" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
