[package]
name = "cid-server"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
description = "Server entrypoint for cid"

[[bin]]
name = "cid"
path = "src/main.rs"

[dependencies]
cid-base = { path = "../base", version = "0.1.1" }
cid-daemon = { path = "../daemon", version = "0.1.1" }
cid-pal = { path = "../pal", version = "0.1.1" }
cid-web = { path = "../web", version = "0.1.1" }
